import { app, BrowserWindow, dialog, ipcMain, Menu, nativeTheme, protocol, safeStorage, session, shell } from 'electron'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { CloseFlow, timeoutAction, type CloseAction, type CloseDecision } from '../shared/flush.ts'
import { asString, parseEntryCreateRequest, parseFlushDone, parseLifecycleRetryRequest, parseNoteName, parseNoteWriteRequest, parseRelocationCommitRequest, parseRelocationPreviewRequest, parseSetPermissionRequest } from '../shared/ipc-guard.ts'
import { IPC } from '../shared/ipc.ts'
import type { AgentStartRequest, AgentStartResult, LifecycleRetryResult, LimitTier, ModelConfigResult, ModelLimitsSetRequest, ModelProfileSetRequest, ModelProvider, ReadingPreference, ReadingSetResult, RelocationCommitResult, RelocationPreviewResult, ThemeMode, ThemeSetResult } from '../shared/ipc.ts'
import type { RemoteImageGetResult } from '../shared/ipc.ts'
import { isThemeMode, loadReadingPreference, loadThemePreference, saveReadingPreference, saveThemePreference } from './theme-preference.ts'
import { isReadingPreference } from '../shared/reading-preference.ts'
import { attachVaultProtocol } from './vault-protocol.ts'
import { RemoteImageService, REMOTE_IMAGE_SCHEME, remoteImageUrl } from './remote-image.ts'
import { attachRemoteImageProtocol } from './remote-image-protocol.ts'
import { VAULT_MEDIA_SCHEME } from '../shared/vault-rel.ts'
import { VaultSession } from './vault.ts'
import { createModelConfigStore, type ModelConfigStore } from './model-config.ts'
import { AgentHost } from './agent-host.ts'
import { modelTierFor } from './permissions.ts'
import { streamModelText } from './model-stream.ts'
import { VaultStructureGate } from './vault-mutation-queue.ts'

protocol.registerSchemesAsPrivileged([
  { scheme: VAULT_MEDIA_SCHEME, privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
  { scheme: REMOTE_IMAGE_SCHEME, privileges: { standard: true, secure: true } }
])

const here = path.dirname(fileURLToPath(import.meta.url))

/** 退出前给渲染进程留的写盘窗口。渲染进程没回应也不能把它卡死在这里。 */
const FLUSH_GRACE_MS = 1000

let mainWindow: BrowserWindow | null = null
let vault: VaultSession | null = null
let quitting = false
let flushed = false
let rendererGone = false
let closeFlow = new CloseFlow()
let flushTimer: NodeJS.Timeout | null = null
let themeMode: ThemeMode = 'system'
let remoteImages: RemoteImageService | null = null
let modelConfig: ModelConfigStore | null = null
let modelConfigError: string | null = null
let agentHost: AgentHost | null = null
let cancellingForClose = false
const lifecycleFlushes = new Map<string, (ok: boolean) => void>()
const structureGate = new VaultStructureGate()
const lifecycleErrorCodes = new Set(['BAD_PATH', 'BAD_REQUEST', 'NO_VAULT', 'VAULT_CHANGED', 'STALE_PREVIEW',
  'STALE_RECOVERY', 'EEXIST', 'ENOENT', 'PATH_CHANGED', 'UNSAFE_PATH', 'PERMISSION_DOWNGRADE',
  'PERMISSION_COLLISION', 'PERMISSIONS_INVALID', 'UNSAVED_DRAFT', 'PREVIOUS_TASK_UNSAVED',
  'LIFECYCLE_RECOVERY_REQUIRED', 'STRUCTURE_BUSY', 'OTHER_TASK_RUNNING', 'ATTACHMENT_COLLISION', 'LINK_SCAN_FAILED'])

function lifecycleError(error: unknown, fallback: string): string {
  return error instanceof Error && lifecycleErrorCodes.has(error.message) ? error.message : fallback
}

function blocksStructureWrite(relPath: string): boolean {
  return !!vault?.root && structureGate.blocksWrite(vault.root, relPath)
}

async function flushBeforeStructure(win: BrowserWindow): Promise<boolean> {
  if (win.isDestroyed() || win.webContents.isDestroyed()) return false
  const id = randomUUID()
  return new Promise<boolean>((resolve) => {
    const timer = setTimeout(() => {
      lifecycleFlushes.delete(id)
      resolve(false)
    }, 120_000)
    lifecycleFlushes.set(id, (ok) => { clearTimeout(timer); lifecycleFlushes.delete(id); resolve(ok) })
    win.webContents.send(IPC.lifecycleFlushRequest, id)
  })
}

function clearFlushTimer(): void {
  if (!flushTimer) return
  clearTimeout(flushTimer)
  flushTimer = null
}

function send(channel: string, payload?: unknown): void {
  const target = mainWindow
  if (!target || target.isDestroyed()) return
  target.webContents.send(channel, payload)
}

async function settleHostBeforeClose(win: BrowserWindow): Promise<boolean> {
  try { await agentHost?.cancelAll('close') } catch { /* pending answer is retained for retry below */ }
  while (agentHost?.hasPending()) {
    try { await agentHost.retryPending() } catch { /* ask the person before discarding generated bytes */ }
    if (!agentHost.hasPending()) break
    const { response } = await dialog.showMessageBox(win, {
      type: 'warning',
      title: '生成内容尚未保存',
      message: '模型已停止，但部分回答或账本写入失败。',
      detail: '可以重试保存、继续编辑，或明确放弃尚未写盘的生成内容。',
      buttons: ['重试保存', '继续编辑', '明确放弃生成内容并关闭'],
      defaultId: 0,
      cancelId: 1,
      noLink: true
    })
    if (response === 1) { quitting = false; return false }
    if (response === 2) { agentHost.discardPending(); break }
  }
  return true
}

function runCloseAction(action: CloseAction, win: BrowserWindow, stalled = false): void {
  if (action === 'none') return
  if (action !== 'flush') clearFlushTimer()
  if (action === 'flush') {
    clearFlushTimer()
    if (win.webContents.isDestroyed()) {
      runCloseAction(closeFlow.rendererGone(), win)
      return
    }
    flushTimer = setTimeout(() => {
      const alive = !rendererGone && !win.isDestroyed() && !win.webContents.isDestroyed()
      // 渲染进程只是挂起（或计时器触发之后才崩）也要给出一条出路，
      // 否则流程停在 flushing，窗口关不掉、Cmd+Q 也被挡住。
      const next = timeoutAction(closeFlow, alive)
      runCloseAction(next, win, next === 'prompt')
    }, FLUSH_GRACE_MS)
    win.webContents.send(IPC.flushRequest)
  } else if (action === 'prompt') {
    const abandon = quitting || process.platform !== 'darwin'
      ? '放弃未保存修改并退出应用'
      : '放弃未保存修改并关闭窗口'
    void dialog.showMessageBox(win, {
      type: 'warning',
      title: stalled ? '保存没有回应' : '笔记尚未保存',
      message: stalled ? '窗口没有在时限内确认写盘结果。' : '写盘失败，仍有未保存的修改。',
      detail: stalled
        ? '可以重试保存、继续编辑，或明确放弃本次未保存的修改。若窗口已无响应，只有后两项可选。'
        : '可以重试保存、继续编辑，或明确放弃本次未保存的修改。',
      buttons: ['重试保存', '继续编辑', abandon],
      defaultId: 0,
      cancelId: 1,
      noLink: true
    }).then(({ response }) => {
      const choice: CloseDecision = response === 0 ? 'retry' : response === 2 ? 'discard' : 'continue'
      runCloseAction(closeFlow.decide(choice), win, stalled)
    }).catch(() => {
      runCloseAction(closeFlow.decide('continue'), win)
    })
  } else if (action === 'cancel') {
    quitting = false
  } else if (action === 'close') {
    flushed = true
    if (quitting) app.quit()
    else if (!win.isDestroyed()) win.close()
  }
}

function createWindow(): void {
  flushed = false
  rendererGone = false
  flushTimer = null
  closeFlow = new CloseFlow()
  const dark = nativeTheme.shouldUseDarkColors
  // 主进程读不到渲染层的 CSS token，所以窗口外观这两个色值是第二份拷贝：
  // 必须与 src/renderer/src/styles.css 的 --surface-nav 同值（日 #f5f6f8 / 夜 #1d2933）。
  // 见 docs/architecture.md「颜色只有一个来源」那一行的已知例外。
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 800,
    minHeight: 560,
    title: 'Rgent',
    backgroundColor: dark ? '#1d2933' : '#f5f6f8',
    ...(process.platform === 'darwin' ? {
      titleBarStyle: 'hiddenInset' as const,
      // hiddenInset 默认交通灯偏上；将原生控件移到 46px tab 栏的中线。
      trafficLightPosition: { x: 13, y: 16 }
    } : {}),
    ...(process.platform === 'win32' ? {
      titleBarStyle: 'hidden' as const,
      titleBarOverlay: {
        color: dark ? '#1d2933' : '#f5f6f8',
        symbolColor: dark ? '#dfe3e8' : '#1c1f23',
        height: 46
      }
    } : {}),
    webPreferences: {
      preload: path.join(here, '../preload/index.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  })
  // 同上的第二份拷贝：跟随系统切换时两处一起改，别只改上面创建时那一处。
  const updateWindowTheme = (): void => {
    const win = mainWindow
    if (!win || win.isDestroyed()) return
    const isDark = nativeTheme.shouldUseDarkColors
    win.setBackgroundColor(isDark ? '#1d2933' : '#f5f6f8')
    if (process.platform === 'win32') win.setTitleBarOverlay({
      color: isDark ? '#1d2933' : '#f5f6f8',
      symbolColor: isDark ? '#dfe3e8' : '#1c1f23',
      height: 46
    })
  }
  nativeTheme.on('updated', updateWindowTheme)

  mainWindow.on('closed', () => {
    nativeTheme.off('updated', updateWindowTheme)
    mainWindow = null
  })
  mainWindow.webContents.on('render-process-gone', () => {
    rendererGone = true
    // 渲染进程没了本身就要推进关窗流程：只置标志的话，若它是在超时之后才崩的，
    // CloseFlow 会永远停在 flushing，窗口再也关不掉。空闲态这里返回 'none'，无副作用。
    const win = mainWindow
    if (win) runCloseAction(closeFlow.rendererGone(), win)
  })

  // 关窗前先写盘；失败时由主进程给出重试、继续编辑或明确放弃的选择。
  mainWindow.on('close', (event) => {
    if (flushed) return
    event.preventDefault()
    const win = mainWindow
    if (!win) return
    if (cancellingForClose) return
    if (agentHost?.active().length || agentHost?.hasPending()) {
      cancellingForClose = true
      void settleHostBeforeClose(win).then((proceed) => {
        if (proceed && !win.isDestroyed()) runCloseAction(closeFlow.request(), win)
      }).finally(() => { cancellingForClose = false })
    } else runCloseAction(closeFlow.request(), win)
  })

  mainWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
  mainWindow.webContents.on('will-navigate', (event, url) => {
    event.preventDefault()
    if (url.startsWith('https://') || url.startsWith('http://')) {
      void shell.openExternal(url)
    }
  })

  const rendererUrl = process.env.ELECTRON_RENDERER_URL
  if (rendererUrl) {
    void mainWindow.loadURL(rendererUrl)
  } else {
    void mainWindow.loadFile(path.join(here, '../renderer/index.html'))
  }
}

function buildMenu(): void {
  const template: Electron.MenuItemConstructorOptions[] = [
    ...(process.platform === 'darwin' ? [{ role: 'appMenu' as const }] : []),
    {
      label: '文件',
      submenu: [
        {
          label: '打开库…',
          accelerator: 'CmdOrCtrl+O',
          click: () => send(IPC.menuOpenVault)
        },
        {
          label: '新建笔记',
          accelerator: 'CmdOrCtrl+N',
          click: () => send(IPC.menuNewNote)
        },
        {
          label: '保存',
          accelerator: 'CmdOrCtrl+S',
          click: () => send(IPC.menuSave)
        },
        { type: 'separator' },
        process.platform === 'darwin' ? { role: 'close' } : { role: 'quit' }
      ]
    },
    { role: 'editMenu' },
    { role: 'viewMenu' }
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

function registerIpc(): void {
  const trusted = (event: Electron.IpcMainInvokeEvent): boolean =>
    Boolean(mainWindow && event.sender === mainWindow.webContents)
  const configResult = (): ModelConfigResult => modelConfig
    ? { ok: true, config: modelConfig.getPublic() }
    : { ok: false, error: modelConfigError ?? 'MODEL_CONFIG_UNAVAILABLE' }
  ipcMain.handle(IPC.modelConfigGet, (event): ModelConfigResult =>
    trusted(event) ? configResult() : { ok: false, error: 'BAD_SENDER' })
  ipcMain.handle(IPC.modelProfileSet, (event, value: unknown): ModelConfigResult => {
    if (!trusted(event) || !modelConfig) return { ok: false, error: 'MODEL_CONFIG_UNAVAILABLE' }
    const request = value as Partial<ModelProfileSetRequest> | null
    if (!request || typeof request !== 'object' || !request.fields || typeof request.fields !== 'object' ||
        (request.newKey !== undefined && typeof request.newKey !== 'string')) return { ok: false, error: 'BAD_REQUEST' }
    try {
      modelConfig.updateProfile(request.provider as ModelProvider, request.fields, request.newKey)
      return configResult()
    } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'IO_ERROR' } }
  })
  ipcMain.handle(IPC.modelSelect, (event, value: unknown): ModelConfigResult => {
    if (!trusted(event) || !modelConfig) return { ok: false, error: 'MODEL_CONFIG_UNAVAILABLE' }
    try { modelConfig.select(value as ModelProvider); return configResult() }
    catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'IO_ERROR' } }
  })
  ipcMain.handle(IPC.modelKeyDelete, (event, value: unknown): ModelConfigResult => {
    if (!trusted(event) || !modelConfig) return { ok: false, error: 'MODEL_CONFIG_UNAVAILABLE' }
    try { modelConfig.deleteKey(value as ModelProvider); return configResult() }
    catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'IO_ERROR' } }
  })
  ipcMain.handle(IPC.modelLimitsSet, (event, value: unknown): ModelConfigResult => {
    if (!trusted(event) || !modelConfig || !value || typeof value !== 'object') return { ok: false, error: 'BAD_REQUEST' }
    const request = value as Partial<ModelLimitsSetRequest>
    try { modelConfig.updateLimits(request.tier as LimitTier, request.limits!); return configResult() }
    catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'IO_ERROR' } }
  })
  ipcMain.handle(IPC.agentTasks, (event) => trusted(event)
    ? agentHost?.active().map(({ id, relPath, startedAt }) => ({ id, relPath, startedAt })) ?? [] : [])
  ipcMain.handle(IPC.agentCancel, async (event, value: unknown) => {
    if (!trusted(event) || typeof value !== 'string' || value.length > 128) return false
    return Boolean(await agentHost?.cancel(value, 'user'))
  })
  ipcMain.handle(IPC.agentStart, async (event, value: unknown): Promise<AgentStartResult> => {
    if (!trusted(event) || !agentHost || !value || typeof value !== 'object') return { ok: false, error: 'BAD_REQUEST' }
    const request = value as Partial<AgentStartRequest>
    if (typeof request.relPath !== 'string' || typeof request.expectedText !== 'string' ||
        typeof request.promptText !== 'string' || request.promptText.length > 20000 ||
        !request.range || !Number.isSafeInteger(request.range.start) || !Number.isSafeInteger(request.range.end)) {
      return { ok: false, error: 'BAD_REQUEST' }
    }
    if (structureGate.isBusy()) return { ok: false, error: 'NOTE_BUSY' }
    try {
      const task = await agentHost.start(request as AgentStartRequest)
      void task.done.catch(() => {})
      return { ok: true, id: task.id }
    } catch (error) { return { ok: false, error: error instanceof Error ? error.message : 'AGENT_START_FAILED' } }
  })
  ipcMain.handle(IPC.remoteImageGet, async (event, value: unknown): Promise<RemoteImageGetResult> => {
    if (!mainWindow || event.sender !== mainWindow.webContents || !remoteImages ||
        !value || typeof value !== 'object' ||
        typeof (value as { url?: unknown }).url !== 'string' ||
        typeof (value as { allowHttp?: unknown }).allowHttp !== 'boolean') {
      return { ok: false, error: 'INVALID_URL' }
    }
    const request = value as { url: string; allowHttp: boolean }
    const result = await remoteImages.load(request.url, request.allowHttp)
    return result.ok ? { ok: true, src: remoteImageUrl(result.token) } : result
  })
  ipcMain.handle(IPC.themeGet, () => themeMode)
  ipcMain.handle(IPC.readingGet, () => loadReadingPreference(app.getPath('userData')))
  ipcMain.handle(IPC.readingSet, (_event, value: unknown): ReadingSetResult => {
    if (!isReadingPreference(value)) return { ok: false, error: 'BAD_READING' }
    try {
      saveReadingPreference(app.getPath('userData'), value)
      return { ok: true, reading: value as ReadingPreference }
    } catch { return { ok: false, error: 'IO_ERROR' } }
  })
  ipcMain.handle(IPC.themeSet, (_event, value: unknown): ThemeSetResult => {
    if (!isThemeMode(value)) return { ok: false, error: 'BAD_MODE' }
    try {
      saveThemePreference(app.getPath('userData'), value)
      themeMode = value
      nativeTheme.themeSource = value === 'day' ? 'light' : value === 'night' ? 'dark' : 'system'
      return { ok: true, mode: value }
    } catch {
      return { ok: false, error: 'IO_ERROR' }
    }
  })
  ipcMain.handle(IPC.vaultGet, () => vault?.currentState() ?? { status: 'needs-pick', reason: 'first-run' })
  ipcMain.handle(IPC.vaultPick, async () => {
    if (!vault) return { status: 'needs-pick', reason: 'first-run' }
    if (structureGate.isBusy()) throw new Error('STRUCTURE_BUSY')
    return vault.pick(mainWindow)
  })
  ipcMain.handle(IPC.treeList, async () => vault?.tree() ?? [])
  ipcMain.handle(IPC.noteRead, async (_event, relPath: unknown) => {
    const pathInVault = asString(relPath)
    if (!pathInVault) throw new Error('BAD_PATH')
    if (!vault) throw new Error('NO_VAULT')
    return vault.read(pathInVault)
  })
  ipcMain.handle(IPC.noteWrite, async (_event, value: unknown) => {
    const request = parseNoteWriteRequest(value)
    if (!request) return { ok: false, error: 'BAD_PATH' }
    if (!vault) return { ok: false, error: 'NO_VAULT' }
    if (blocksStructureWrite(request.relPath)) return { ok: false, error: 'NOTE_BUSY' }
    try {
      const revision = await vault.write(request.relPath, request.content, request.expectedRevision)
      return { ok: true, revision }
    } catch (err) {
      return { ok: false, error: err instanceof Error && err.message === 'CONFLICT' ? 'CONFLICT' : 'IO_ERROR' }
    }
  })
  ipcMain.handle(IPC.permissionsGet, async () => vault?.permissions() ?? { status: 'invalid', error: '未选择库' })
  ipcMain.handle(IPC.permissionsSet, async (_event, value: unknown) => {
    const request = parseSetPermissionRequest(value)
    if (!request) throw new Error('BAD_PERMISSION')
    if (!vault) throw new Error('NO_VAULT')
    return vault.setPermission(request.relPath, request.tier)
  })
  ipcMain.handle(IPC.noteCreate, async (_event, name: unknown) => {
    const request = typeof name === 'string'
      ? { name: parseNoteName(name), parent: '' }
      : parseEntryCreateRequest(name)
    if (!request?.name) throw new Error('BAD_PATH')
    if (!vault) throw new Error('NO_VAULT')
    return vault.create(request.name, request.parent)
  })
  ipcMain.handle(IPC.folderCreate, async (_event, value: unknown) => {
    const request = parseEntryCreateRequest(value)
    if (!request || !vault) throw new Error('BAD_PATH')
    return vault.createFolder(request.name, request.parent)
  })
  ipcMain.handle(IPC.relocationPreview, async (event, value: unknown): Promise<RelocationPreviewResult> => {
    const request = parseRelocationPreviewRequest(value)
    const currentVault = vault
    if (!trusted(event) || !request || !currentVault) return { ok: false, error: 'BAD_PATH' }
    try {
      const token = currentVault.captureSession()
      const root = currentVault.root!
      if (structureGate.isBusy()) throw new Error('STRUCTURE_BUSY')
      await agentHost?.whenLaunchesSettled()
      currentVault.assertSession(token)
      const affected = agentHost?.active().filter((task) => task.root === root &&
        (task.relPath === request.source ||
          (request.kind === 'folder' && task.relPath.startsWith(`${request.source}/`)) ||
          (request.kind === 'note' && task.relPath.startsWith(`${request.source.slice(0, -3)}/`)))) ?? []
      for (const task of affected) { await agentHost?.cancel(task.id, 'user'); currentVault.assertSession(token) }
      if (agentHost?.hasPending(root)) throw new Error('PREVIOUS_TASK_UNSAVED')
      if (!mainWindow || !(await flushBeforeStructure(mainWindow))) throw new Error('UNSAVED_DRAFT')
      currentVault.assertSession(token)
      const preview = await currentVault.previewRelocation(request, token)
      currentVault.assertSession(token)
      return { ok: true, preview: {
        id: preview.id, sessionId: preview.sessionId, kind: preview.kind, source: preview.source, target: preview.target,
        moves: preview.moves,
        linkChanges: preview.linkChanges.map(({ relPath, newPath, changes }) => ({ relPath, newPath, count: changes.length })),
        permissionChanges: preview.permissionChanges
      } }
    } catch (error) { return { ok: false, error: lifecycleError(error, 'PREVIEW_FAILED') } }
  })
  ipcMain.handle(IPC.relocationCommit, async (event, value: unknown): Promise<RelocationCommitResult> => {
    const request = parseRelocationCommitRequest(value)
    const win = mainWindow
    const currentVault = vault
    if (!trusted(event) || !request || !currentVault || !win || !currentVault.root) return { ok: false, error: 'BAD_REQUEST' }
    const token = currentVault.captureSession()
    const root = currentVault.root
    const preview = currentVault.relocationPreviewById(request.id)
    if (!preview) return { ok: false, error: 'STALE_PREVIEW' }
    if (structureGate.isBusy()) return { ok: false, error: 'STRUCTURE_BUSY' }
    structureGate.begin({
      root,
      exact: [preview.source, ...(request.repairLinks ? preview.linkChanges.map((item) => item.relPath) : [])],
      prefixes: preview.kind === 'folder' ? [preview.source] : [preview.source.slice(0, -3)]
    })
    try {
      await agentHost?.whenLaunchesSettled()
      currentVault.assertSession(token)
      const affected = agentHost?.active().filter((task) => task.root === root && structureGate.affects(root, task.relPath)) ?? []
      if (agentHost?.active().some((task) => task.root === root && !structureGate.affects(root, task.relPath))) {
        throw new Error('OTHER_TASK_RUNNING')
      }
      for (const task of affected) { await agentHost?.cancel(task.id, 'user'); currentVault.assertSession(token) }
      if (agentHost?.hasPending(root)) throw new Error('PREVIOUS_TASK_UNSAVED')
      if (!(await flushBeforeStructure(win))) throw new Error('UNSAVED_DRAFT')
      currentVault.assertSession(token)
      structureGate.seal()
      const outcome = await currentVault.commitRelocation(request.id, request.repairLinks, token)
      currentVault.assertSession(token)
      return { ok: true, moved: outcome.moved.map(({ from, to }) => ({ from, to })), unrepaired: outcome.unrepaired }
    } catch (error) { return { ok: false, error: lifecycleError(error, 'COMMIT_FAILED') } }
    finally { structureGate.finish() }
  })
  ipcMain.handle(IPC.lifecycleStatus, async (event) => {
    if (!trusted(event) || !vault) throw new Error('NO_VAULT')
    return vault.lifecycleStatus()
  })
  ipcMain.handle(IPC.lifecycleRetry, async (event, value: unknown): Promise<LifecycleRetryResult> => {
    const request = parseLifecycleRetryRequest(value)
    const currentVault = vault
    const win = mainWindow
    if (!trusted(event) || !request || !currentVault || !win) return { ok: false, error: 'BAD_REQUEST' }
    if (structureGate.isBusy()) return { ok: false, error: 'STRUCTURE_BUSY' }
    let entered = false
    try {
      currentVault.assertSession(request.sessionId)
      const root = currentVault.root!
      const scope = currentVault.lifecycleRecoveryScope(request)
      structureGate.begin({ root, exact: scope.relPaths, prefixes: scope.moved.flatMap((move) => [move.from, move.to]) })
      entered = true
      await agentHost?.whenLaunchesSettled()
      currentVault.assertSession(request.sessionId)
      // An active recovery record already fails all model requests closed.
      // Stop streams; keep unrelated unsaved output in Host memory until policy is stable again.
      try { await agentHost?.cancelAll('user', root) } catch { /* pending paths are checked below */ }
      currentVault.assertSession(request.sessionId)
      if (agentHost?.pendingPaths(root).some((relPath) => structureGate.affects(root, relPath))) {
        throw new Error('PREVIOUS_TASK_UNSAVED')
      }
      if (!(await flushBeforeStructure(win))) throw new Error('UNSAVED_DRAFT')
      currentVault.assertSession(request.sessionId)
      structureGate.seal()
      const outcome = await currentVault.lifecycleRetry(request)
      currentVault.assertSession(request.sessionId)
      try { await agentHost?.retryPending(root) } catch { /* retain output; structural recovery succeeded */ }
      currentVault.assertSession(request.sessionId)
      return { ok: true, moved: outcome.moved.map(({ from, to }) => ({ from, to })), unrepaired: outcome.unrepaired,
        hostPending: agentHost?.hasPending(root) ?? false }
    } catch (error) { return { ok: false, error: lifecycleError(error, 'LIFECYCLE_RECOVERY_REQUIRED') } }
    finally { if (entered) structureGate.finish() }
  })
  ipcMain.on(IPC.lifecycleFlushDone, (event, value: unknown) => {
    if (!mainWindow || event.sender !== mainWindow.webContents || !value || typeof value !== 'object') return
    const response = value as { id?: unknown; ok?: unknown }
    if (typeof response.id === 'string') lifecycleFlushes.get(response.id)?.(response.ok === true)
  })
  ipcMain.handle(IPC.backlinks, async (_event, relPath: unknown) => {
    const pathInVault = asString(relPath)
    if (!pathInVault) return []
    return vault?.backlinks(pathInVault) ?? []
  })
  ipcMain.handle(IPC.search, async (_event, query: unknown) => {
    const text = asString(query)
    if (text == null) return []
    return vault?.search(text) ?? []
  })
  ipcMain.on(IPC.flushDone, (event, payload: unknown) => {
    const win = mainWindow
    if (!win || event.sender !== win.webContents) return
    runCloseAction(closeFlow.flushed(parseFlushDone(payload).ok), win)
  })
}

app.whenReady().then(() => {
  themeMode = loadThemePreference(app.getPath('userData'))
  nativeTheme.themeSource = themeMode === 'day' ? 'light' : themeMode === 'night' ? 'dark' : 'system'
  try { modelConfig = createModelConfigStore(app.getPath('userData'), safeStorage) }
  catch (error) { modelConfigError = error instanceof Error ? error.message : 'MODEL_CONFIG_UNAVAILABLE' }
  vault = new VaultSession(app.getPath('userData'), send, async (previous) => {
    if (structureGate.isBusy()) throw new Error('STRUCTURE_BUSY')
    try { await agentHost?.cancelAll('vault-change', previous) } catch { /* pending retry below */ }
    await agentHost?.retryPending(previous)
    if (agentHost?.hasPending(previous)) throw new Error('生成内容尚未保存，不能换库')
    if (structureGate.isBusy()) throw new Error('STRUCTURE_BUSY')
  })
  vault.restore()
  agentHost = new AgentHost({
    root: () => vault?.root ?? null,
    read: (relPath) => vault!.read(relPath),
    write: (relPath, content, revision) => {
      if (blocksStructureWrite(relPath)) throw new Error('NOTE_BUSY')
      return vault!.write(relPath, content, revision)
    },
    tier: modelTierFor,
    credential: () => {
      if (!modelConfig) throw new Error(modelConfigError ?? 'MODEL_CONFIG_UNAVAILABLE')
      const selected = modelConfig.getPublic().selected
      return modelConfig.credential(selected)
    },
    limits: () => {
      if (!modelConfig) throw new Error(modelConfigError ?? 'MODEL_CONFIG_UNAVAILABLE')
      return modelConfig.getPublic().limits.none
    },
    stream: (input, signal) => streamModelText({ ...input, signal }),
    emit: ({ root, ...event }) => {
      if (vault?.root === root) send(IPC.agentEvent, event)
    }
  })
  attachVaultProtocol(() => vault)
  const imageSession = session.fromPartition('rgent-remote-images')
  remoteImages = new RemoteImageService((url, init) => imageSession.fetch(url, init))
  attachRemoteImageProtocol(remoteImages)
  registerIpc()
  buildMenu()
  createWindow()
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('before-quit', () => {
  quitting = true
})

// 必须等渲染进程写完盘再拆库：退出前那次 flush 还要经 noteWrite 落盘。
app.on('will-quit', () => {
  vault?.dispose()
})
